### ISSUE TITLE
404 on webserver

### ISSUE THREAD

**Issue by Algirdas-Z** [hostinger/litespeed_exporter#2]
For testing purposes, exporter installed here:

http://xxx:9114/

Getting 404, is it because of misconfiguration (which is possible) or something internal ?

**Comment by ton31337** [comment]
http://us-gcp1-web911.main-hosting.eu:9114/metrics

**Comment by Algirdas-Z** [comment]
woops, my bad, however root dir should have link to /metrics

**Comment by laurynasgadl** [comment]
Will add the landing page

**Comment by laurynasgadl** [comment]
Added in v0.0.3
