### ISSUE TITLE
Metrics with empty labels

### ISSUE THREAD

**Issue by Algirdas-Z** [hostinger/litespeed_exporter#4]
Looks like metrics has empty labels

http://:9114/metrics
```
litespeed_req_rate_tot_reqs{core="",hostname=""} 7.459172e+06
```

I think these could be removed, hostname label is probably the same as "instance" label added by prometheus, so no need to duplicate it.

**Comment by laurynasgadl** [comment]
These are filled if the exporter is run with the `litespeed.metrics-by-core`, `litespeed.req-rates-by-host` flags. Core indicates the report filename for a specific core (eg. `.rtreport.2`, `.rtreport.3`), hostname indicates which vhost the metric is for. Example of how it would look like: https://github.com/hostinger/litespeed_exporter/blob/master/testdata/some_filtered_by_host.metrics
